export const WEEK_LOAD = 'Week/Load'
export const WEEK_LOADING = 'Week/Loading'
export const WEEK_FAIL = 'Week/Fail'
export const WEEK_INITIAL_DATA = 'Week/InitialData'
export const SET_DOB = 'Week/SetDob'